spring:
  datasource:
    url: jdbc:h2:~/data/eatgo
  jpa:
    hibernate:
      ddl-auto: update
jwt:
  secret: 1234567890123456789testsecretkey

---

spring:
  profiles: test
  datasource:
    url: jdbc:h2:mem:test